### ISSUE TITLE
Restructure codebase to be more scalable

### ISSUE THREAD

**Issue by nickeidler** [UCSB-CS56-Projects/cs56-games-states-quiz#12]
Right now the codebase is rather inflexible and difficult to scale.  Make it easier to scale by reworking the codebase.
Specifically, the following class files are heavily coupled to each other and should be decoupled, made more efficient, and made more flexible with scalability in mind.
* GamePanel.java
* MapPanel.java

~300pts

**Comment by mliou** [comment]
Approved.
