### ISSUE TITLE
GUI improvement

### ISSUE THREAD

**Issue by ryankemper** [UCSB-CS56-Projects/cs56-games-states-quiz#16]
There are a number of small changes that could be made to improve the usability of the user interface. For example:

- At game start, bottom button "state then capital" is cut off ("State then Cap..") 
- In the "state then capital" mode, when a capital is incorrectly guessed, the user has to re-click the original state. Instead, the game should simply re-prompt the user for the capital.
- The top of the JFrame says "you think you know US States?", but it could change to reflect the current game mode

~estimated 100

**Comment by ashedden** [comment]
Approved! ~100
