### ISSUE TITLE
Updating the QuestionTextArea

### ISSUE THREAD

**Issue by rowallen** [UCSB-CS56-Projects/cs56-games-states-quiz#18]
Restructure how the game writes to the question text area and prompts the user for the next question.
For example, instead of saying "Nope!" the game could tell the player which state they incorrectly picked, which would ultimately lead to a better educational experience.

~estimated 100

**Comment by ashedden** [comment]
W16 ok!

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed with this [pull request](https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/27).
