### ISSUE TITLE
Update the End of the Game

### ISSUE THREAD

**Issue by rowallen** [UCSB-CS56-Projects/cs56-games-states-quiz#19]
Right now the player has to completely exit the game when he/she finishes.  Edit the ending of the game.

For example, when the player finishes the game have the game prompt the player for a new game.  Have a window pop up asking the player if he/she wants to play another game.

~estimated 100

**Comment by ashedden** [comment]
W16 ok!

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed with this [pull request](https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/27).
