### ISSUE TITLE
Update the Help/Hint button

### ISSUE THREAD

**Issue by rowallen** [UCSB-CS56-Projects/cs56-games-states-quiz#20]
Right now the help/hint button only provides the quadrant the state is in.  This is useless for someone trying to guess the capital of the state in StateThenCapital mode.  Make the hint more diverse and descriptive.

~estimated 200

**Comment by ashedden** [comment]
W16 ok!

**Comment by jimmylle** [comment]
F16 OK (200 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/28).
