### ISSUE TITLE
StateThenCapital mode NullPointerException

### ISSUE THREAD

**Issue by rowallen** [UCSB-CS56-Projects/cs56-games-states-quiz#21]
In StateThenCapital mode if you hit 'cancel' when trying to guess the capital, a null pointer exception is thrown because the method quit without receiving a boolean.  Fix this so that the exception is caught.

~estimated 100

**Comment by ashedden** [comment]
W16 ok!

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed in this [pul request](https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/31).
