### ISSUE TITLE
Add Sound Effects

### ISSUE THREAD

**Issue by rowallen** [UCSB-CS56-Projects/cs56-games-states-quiz#22]
Add separate sound effects for correct answers, incorrect answers and completing the game.

~estimated 250

**Comment by ashedden** [comment]
W16 ok!

**Comment by jimmylle** [comment]
F16 OK (200 pts)

**Comment by jimmylle** [comment]
Fixed with this [pull request](https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/27).
