### ISSUE TITLE
Add a timer

### ISSUE THREAD

**Issue by vchandran2** [UCSB-CS56-Projects/cs56-games-states-quiz#29]
Add a timer which keeps track of how long you take to complete the game. Maybe in hard mode, every wrong answer could add 2 seconds.

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/31).
