### ISSUE TITLE
Record a different high score for each game mode

### ISSUE THREAD

**Issue by vincentwangg** [UCSB-CS56-Projects/cs56-games-states-quiz#32]

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by xavierholt** [comment]
Removing the "encryption" part 'cause it's silly.  Points stay the same.

100 XP

**Comment by xavierholt** [comment]
Added in https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/56. See https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/56 for the exception that gets thrown when the files are missing.

+100 XP
