### ISSUE TITLE
Improve Question Text Area

### ISSUE THREAD

**Issue by vincentwangg** [ucsb-cs56-projects/cs56-games-states-quiz#34]
Find a new way to tell the player that their answer is incorrect, otherwise if they keep guessing incorrectly, the question text area gets flooded with messages. For example, it will keep saying "Answer is incorrect! Answer is incorrect! Answer is incorrect! Answer is incorrect! Answer is incorrect!"

**Comment by vincentwangg** [comment]
Find a new way to tell the player that their answer is incorrect, otherwise if they keep guessing incorrectly, the question text area gets flooded with messages. For example, it will keep saying "Incorrect! Incorrect! Incorrect! Incorrect! Incorrect! Incorrect! Incorrect! Incorrect! Incorrect! Incorrect! Incorrect!"

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by xavierholt** [comment]
Seems fixed as of F17.

**Comment by xavierholt** [comment]
Never mind - found it.  This is only a problem when entering capital names in "States then Capitals" mode.  Reducing points.

50 XP

**Comment by SElegans** [comment]
W18 OK (50pts)

**Comment by steve-fields** [comment]
W18 CLOSED
