### ISSUE TITLE
Nicknames in High Scores

### ISSUE THREAD

**Issue by vincentwangg** [UCSB-CS56-Projects/cs56-games-states-quiz#36]
With each high score, add a nickname just like how arcade games do.

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by xavierholt** [comment]
Name functionality added by https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/56.  Created https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/issues/59 to deal with the exceptions that are thrown if the file doesn't exist.
