### ISSUE TITLE
State Buttons and Game Modes

### ISSUE THREAD

**Issue by vincentwangg** [ucsb-cs56-projects/cs56-games-states-quiz#38]
When pressing on the state buttons in any of the game modes (states, capitals, states and capitals), the buttons will disappear if the player is playing in hard mode and the button will not disappear if the player is playing in easy/normal mode. This should be the other way around so that if the player is playing in hard mode, the buttons do not disappear and if the player is playing in easy/normal mode, the buttons will disappear.

**Comment by vincentwangg** [comment]
When pressing on the state buttons in any of the game modes (states, capitals, states and capitals), the buttons will disappear if the player is playing in hard mode and the button will not disappear if the player is playing in easy/normal mode. This should be the other way around so that if the player is playing in hard mode, the buttons do not disappear and if the player is playing in easy/normal mode, the buttons will disappear.

**Comment by jimmylle** [comment]
F16 OK (150 pts)

**Comment by xavierholt** [comment]
Bumping the points a little, and clarifying the requirements.

**Hard:**  Buttons should never disappear.

**Medium:**  Incorrectly clicked buttons should disappear, then reappear once the correct button is clicked.  The correct button _should not_ disappear.

**Easy:**  Incorrectly clicked buttons should disappear, then reappear once the correct button is clicked.  The correct button _should_ disappear when clicked.

200 XP

**Comment by xavierholt** [comment]
This is a little better after the changes made in fall 2017, but not fully fixed.  Easy mode now behaves as intended, but the behaviors of Medium and Hard mode are flipped.

+100 XP for the fall 2017 group.

This issue remains open for whoever wants to fix Medium and Hard.  The conflation of game _length_ and game _difficulty_ in https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/issues/40 might make this harder.  Maybe make a new issue to make those two things independent again?

**Comment by SElegans** [comment]
W18 OK (100pts)

**Comment by steve-fields** [comment]
W18 CLOSED
