### ISSUE TITLE
Friendlier Capital Entry

### ISSUE THREAD

**Issue by xavierholt** [ucsb-cs56-projects/cs56-games-states-quiz#49]
"States then Capitals" mode is super picky when you have to type the capital name.  Relax it a bit.
 
~Simple (50 XP):  It would be less typo-prone (and more [eagle-friendly](http://hyperboleandahalf.blogspot.com/2010/04/alot-is-better-than-you-at-everything.html)) if it didn't care about capitalization.~

Advanced (100 XP):  If you're close, it should tell you that.  This is discouraging:
> **PC:** What's the capital of Idaho?
> **Me:** Biose
> **PC:** NOPE!

This lets you retain some dignity:
> **PC:** What's the capital of Idaho?
> **Me:** Biose
> **PC:** Close!
> **Me:** Boise
> **PC:** Yay!

**Comment by xavierholt** [comment]
Simple version is fixed with https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/60 and https://github.com/UCSB-CS56-Projects/cs56-games-states-quiz/pull/57.

+50 XP

Advanced version os still open for next quarter!

**Comment by SElegans** [comment]
W18 OK (150pts)

**Comment by steve-fields** [comment]
W18 CLOSED
