### ISSUE TITLE
Game Starts Without Using Start Button

### ISSUE THREAD

**Issue by diana-reyes** [ucsb-cs56-projects/cs56-games-states-quiz#62]
The game can be started without the timer being turned on by pressing the "start" button. The player should not be able to start to guess states without first pressing the start button. Time needs to be started in order for it to be recorded.

150 XP

**Comment by xavierholt** [comment]
F17 OK: 200 XP

**Comment by SElegans** [comment]
W18 OK (200pts)

**Comment by steve-fields** [comment]
W18 CLOSED
