### ISSUE TITLE
Make Score Visible At All Times

### ISSUE THREAD

**Issue by diana-reyes** [ucsb-cs56-projects/cs56-games-states-quiz#64]
Currently, the game score is not visible at all times. It disappears when the wrong state is clicked, but shows up again when the correct state is clicked.

100 XP

**Comment by xavierholt** [comment]
F17 OK: 100 XP

**Comment by SElegans** [comment]
W18 OK (100pts)

**Comment by steve-fields** [comment]
W18 CLOSED
