### ISSUE TITLE
Change "Cancel" to "Skip"

### ISSUE THREAD

**Issue by diana-reyes** [ucsb-cs56-projects/cs56-games-states-quiz#66]
In "States then Capitals" mode, instead of "cancel" it should say "Skip" when you are entering a capital name. 

50 XP

**Comment by xavierholt** [comment]
If this is a built-in Java dialog box, this might be harder than you think...

F17 OK: 50 - 100 XP

**Comment by SElegans** [comment]
W18 OK (50pts)

**Comment by steve-fields** [comment]
W18 CLOSED
